//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileNameResolver.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileNameResolver.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled during the file renaming operation..
        /// </summary>
        internal static string BackgroundWorker_Cancelled {
            get {
                return ResourceManager.GetString("BackgroundWorker_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files and folders were processed, and {1} files and folders failed to be processed with errors..
        /// </summary>
        internal static string BackgroundWorker_Done {
            get {
                return ResourceManager.GetString("BackgroundWorker_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error during the rename file operation interrupted the operation and it cannot be continued. The error encountered is as follows: {0}.
        /// </summary>
        internal static string BackgroundWorker_Error {
            get {
                return ResourceManager.GetString("BackgroundWorker_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} could not be found..
        /// </summary>
        internal static string DirectoryNotFoundException_Message {
            get {
                return ResourceManager.GetString("DirectoryNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be found..
        /// </summary>
        internal static string FileNotFoundException_Message {
            get {
                return ResourceManager.GetString("FileNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop individual files or folders onto this window. This tool will change all of the filenames encoding to suit your purposes..
        /// </summary>
        internal static string InstructionLabel_Text {
            get {
                return ResourceManager.GetString("InstructionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Resolver.
        /// </summary>
        internal static string MainForm_Text {
            get {
                return ResourceManager.GetString("MainForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Windows/OneDrive.
        /// </summary>
        internal static string ToFormCRadioButton_Text {
            get {
                return ResourceManager.GetString("ToFormCRadioButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For macOS/iCloud.
        /// </summary>
        internal static string ToFormDRadioButton_Text {
            get {
                return ResourceManager.GetString("ToFormDRadioButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock files downloaded from the Internet.
        /// </summary>
        internal static string UnblockFiles_Text {
            get {
                return ResourceManager.GetString("UnblockFiles_Text", resourceCulture);
            }
        }
    }
}
